# src/optimization/procurement.py
"""
DATA-DRIVEN PROCUREMENT SOLVER
Optimizes sourcing decisions based on SAA Inventory Plan & Supplier Constraints.
"""

import os
import pandas as pd
import numpy as np
import pulp
from config.settings import ProjectConfig as Cfg
from src.utils.geo import GeoUtils

class ProcurementOptimizer:
    """
    Optimizes procurement allocation (Split Orders vs Consolidation)
    Inputs:
    - SAA Inventory Plan (Demand & Safety Stock)
    - Supplier Network (Capacity, Fixed Costs, Lead Times)
    """
    
    def __init__(self):
        os.makedirs(Cfg.OUT_DIR_PROCUREMENT, exist_ok=True)
        self.unified = pd.DataFrame()
        self.suppliers = pd.DataFrame()
        self.supplier_product = pd.DataFrame()
    
    def run_with_constraints(self, max_lead_time_days=None, review_period_days=None, 
                             transport_feedback=None):
        """Main optimization routine"""
        self._load_data()
        
        # Determine active constraints
        active_review = review_period_days if review_period_days else Cfg.PROCURE_REVIEW_DAYS
        
        # Build candidate matrix (Store-Product-Supplier combinations)
        candidates = self._build_candidates(max_lead_time_days, active_review, transport_feedback)
        
        if candidates.empty:
            print(f"    [X] Infeasible: No valid sourcing candidates found.")
            return pd.DataFrame(), pd.DataFrame(), pd.DataFrame(), "Infeasible"
        
        # Solve MILP
        return self._solve_milp(candidates)
    
    def _load_data(self):
        """Load Data from Artifacts (Generated by Planner & Network Gen)"""
        # 1. Demand Plan (from Inventory Planner)
        # Note: Reading the 'Enhanced' version which includes SAA quantities
        path_unified = os.path.join(Cfg.ARTIFACTS_DIR, "unified_for_procurement_enhanced.parquet")
        self.unified = pd.read_parquet(path_unified)
        
        # 2. Suppliers Master
        self.suppliers = pd.read_csv(os.path.join(Cfg.ARTIFACTS_DIR, "suppliers.csv"))
        
        # 3. Supplier-Product Constraints (Capacity, Price)
        self.supplier_product = pd.read_csv(os.path.join(Cfg.ARTIFACTS_DIR, "supplier_product.csv"))
        
        # Type enforcement for safe merging
        self.unified['store_id'] = self.unified['store_id'].astype(str)
        self.unified['product_id'] = self.unified['product_id'].astype(str) # String ID consistent
        
        self.suppliers['supplier_id'] = self.suppliers['supplier_id'].astype(int)
        
        self.supplier_product['supplier_id'] = self.supplier_product['supplier_id'].astype(int)
        self.supplier_product['product_id'] = self.supplier_product['product_id'].astype(str)
        
        print(f"\n    [Procurement Load] Stores: {self.unified['store_id'].nunique()}, "
              f"Suppliers: {self.suppliers['supplier_id'].nunique()}, "
              f"SP Matrix: {len(self.supplier_product)}")
    
    def _build_candidates(self, max_lead_time_days, active_review_period, transport_feedback=None):
        """
        Construct feasible sourcing arcs (Candidate Generation)
        """
        # Index lookups for speed
        sup_loc = self.suppliers.set_index('supplier_id').to_dict(orient='index')
        spp_grouped = self.supplier_product.groupby('product_id')
        
        rows = []
        if transport_feedback is None: transport_feedback = {}
        
        for _, plan_row in self.unified.iterrows():
            # Skip items with 0 order quantity (Optimization filtering)
            if plan_row['order_qty_units'] <= 0:
                continue
                
            store_id = str(plan_row['store_id'])
            prod_id = str(plan_row['product_id'])
            
            # Demand Quantity (Units)
            # Logic: Inventory Planner already calculated 'order_qty_units' based on SAA.
            # We just need to fulfill this amount. 
            # Note: active_review_period might scale it if Plan was daily, but Plan is usually "per cycle".
            # Assuming 'order_qty_units' is the TOTAL need for the cycle.
            qty_needed = plan_row['order_qty_units']
            
            # Find viable suppliers
            if prod_id not in spp_grouped.groups:
                continue
            
            possible_suppliers = spp_grouped.get_group(prod_id)
            
            for _, sp in possible_suppliers.iterrows():
                sid = int(sp['supplier_id'])
                if sid not in sup_loc: continue
                
                # Geo Calculations
                s_info = sup_loc[sid]
                s_lat = s_info.get('lat', s_info.get('sup_lat', 0))
                s_lon = s_info.get('lon', s_info.get('sup_lon', 0))
                
                dist_km = GeoUtils.haversine_km(
                    plan_row['store_lat'], plan_row['store_lon'], s_lat, s_lon
                )
                
                # Lead Time & Freshness
                lt_mean = float(sp.get('lead_time_mean_days', 2.0))
                elapsed = float(sp.get('elapsed_shelf_days', 0.0))
                
                # Transport Time (approx)
                transport_days = (dist_km / Cfg.SPEED_KMPH) / 24.0
                total_cycle_time = max(lt_mean, transport_days)
                
                # --- CONSTRAINTS ---
                # 1. Lead Time Check
                if max_lead_time_days and total_cycle_time > max_lead_time_days:
                    continue
                    
                # 2. Shelf Life Check
                shelf_life = float(plan_row.get('shelf_life', 5.0))
                freshness_loss = elapsed + total_cycle_time
                if freshness_loss >= shelf_life:
                    continue # Item spoils before arrival
                
                # --- COSTS ---
                # Transport Cost (Feedback Loop or Static)
                unit_weight = float(plan_row.get('unit_weight_kg', 1.0))
                
                if sid in transport_feedback:
                    # Variable transport cost from Logistics (Allocated per kg)
                    t_cost_unit = transport_feedback[sid] * unit_weight
                else:
                    # Fallback linear distance cost
                    t_cost_unit = Cfg.TRANSPORT_COST_PER_KG_KM * dist_km * unit_weight
                
                base_price = float(sp['unit_price'])
                total_unit_cost = base_price + t_cost_unit
                
                # Supplier Fixed Cost (Per order/link)
                fixed_cost = float(sp.get('fixed_order_cost', Cfg.FIXED_ORDER_COST))
                
                rows.append({
                    'store_id': store_id,
                    'product_id': prod_id,
                    'supplier_id': sid,
                    'total_cost_per_unit': total_unit_cost,
                    'fixed_order_cost': fixed_cost,
                    'min_order_qty_units': int(sp.get('min_order_qty_units', 1)),
                    'demand_units': qty_needed,
                    'unit_weight_kg': unit_weight,
                    'supplier_capacity_kg': float(sp.get('supplier_capacity_kg', 1e6)),
                    'unit_price': base_price,
                    'freshness_loss_days': freshness_loss,
                    'distance_km': dist_km
                })
        
        df = pd.DataFrame(rows)
        
        if not df.empty:
            # Deduplicate just in case
            df = df.drop_duplicates(subset=['store_id', 'product_id', 'supplier_id'])
            print(f"    [Candidates] Generated {len(df)} feasible sourcing options.")
            
        return df
    
    def _solve_milp(self, cand_df):
        """Solve using PuLP (MILP)"""
        # Create unique key for variables
        cand_df['key'] = list(zip(cand_df['store_id'], cand_df['product_id'], cand_df['supplier_id']))
        cand_map = cand_df.set_index('key').to_dict(orient='index')
        keys = cand_df['key'].tolist()
        
        prob = pulp.LpProblem("Procurement_Opt", pulp.LpMinimize)
        
        # --- Variables ---
        # q: Quantity ordered (Units)
        q = pulp.LpVariable.dicts("q", keys, lowBound=0, cat='Integer' if Cfg.ROUND_Q_TO_INT else 'Continuous')
        # y: Binary activation (1 if order placed on this link)
        y = pulp.LpVariable.dicts("y", keys, cat='Binary')
        
        # Big-M Logic
        bigM = {}
        for k in keys:
            # M must be >= Max possible order
            # Limited by Demand or Capacity
            dem = cand_map[k]['demand_units']
            cap_units = cand_map[k]['supplier_capacity_kg'] / max(0.1, cand_map[k]['unit_weight_kg'])
            bigM[k] = min(dem, cap_units) * 1.5 + 10 # Buffer
            
        # --- Objective ---
        # Min(Variable Cost + Fixed Cost + Freshness Penalty)
        obj_terms = []
        fresh_penalty_rate = Cfg.FRESHNESS_PENALTY_PER_DAY
        
        for k in keys:
            r = cand_map[k]
            # Cost = (UnitCost * q) + (Fixed * y) + (Penalty * Price * FreshLoss * q)
            penalty = fresh_penalty_rate * r['unit_price'] * r['freshness_loss_days']
            term = (r['total_cost_per_unit'] + penalty) * q[k] + r['fixed_order_cost'] * y[k]
            obj_terms.append(term)
            
        prob += pulp.lpSum(obj_terms)
        
        # --- Constraints ---
        
        # 1. Demand Satisfaction
        # Sum(q) from all suppliers >= Needed
        for (store, prod), grp in cand_df.groupby(['store_id', 'product_id']):
            relevant_keys = grp['key'].tolist()
            # Allow shortage? If NO, constraint is >= Demand.
            # If YES, we might relax this, but let's assume we want to meet plan.
            # SAA Plan already accounts for risk, so we should try to fill it.
            needed = grp['demand_units'].iloc[0]
            prob += (pulp.lpSum([q[k] for k in relevant_keys]) >= needed, f"Dem_{store}_{prod}")
            
        # 2. Supplier Capacity
        # Sum(q * weight) <= Cap
        for sid, grp in cand_df.groupby('supplier_id'):
            relevant_keys = grp['key'].tolist()
            cap = grp['supplier_capacity_kg'].iloc[0]
            prob += (pulp.lpSum([q[k] * cand_map[k]['unit_weight_kg'] for k in relevant_keys]) <= cap, f"Cap_{sid}")
            
        # 3. Activation & MOQ
        for k in keys:
            prob += (q[k] <= bigM[k] * y[k], f"LinkOn_{k}")
            prob += (q[k] >= cand_map[k]['min_order_qty_units'] * y[k], f"MOQ_{k}")
            
        # --- Solve ---
        solver = pulp.PULP_CBC_CMD(msg=0, timeLimit=Cfg.MAX_SOLVE_TIME_S, gapRel=Cfg.GAP_REL)
        prob.solve(solver)
        
        status = pulp.LpStatus.get(prob.status, "Unknown")
        print(f"    [Solver] Status: {status}, Obj: ${pulp.value(prob.objective):,.2f}")
        
        if status != "Optimal":
            print("    [Warning] Optimization might be sub-optimal or infeasible.")
            
        # --- Extract Results ---
        results = []
        for k in keys:
            q_val = q[k].value()
            if q_val and q_val > 0.1:
                r = cand_map[k]
                results.append({
                    'store_id': k[0],
                    'product_id': k[1],
                    'supplier_id': k[2],
                    'order_qty_units': q_val,
                    'order_weight_kg': q_val * r['unit_weight_kg'],
                    'unit_price': r['unit_price'],
                    'fixed_cost': r['fixed_order_cost'] if y[k].value() > 0.5 else 0,
                    'transport_cost_est': (r['total_cost_per_unit'] - r['unit_price']) * q_val,
                    'freshness_loss_days': r['freshness_loss_days']
                })
                
        sol_df = pd.DataFrame(results)
        
        # Aggregation for Logistics module
        if not sol_df.empty:
            agg_df = sol_df.groupby(['supplier_id', 'store_id'])['order_weight_kg'].sum().reset_index()
            agg_df.rename(columns={'order_weight_kg': 'total_kg'}, inplace=True)
        else:
            agg_df = pd.DataFrame()
            
        return sol_df, agg_df, pd.DataFrame(), status